### ISSUE TITLE
Person isQualified Position

### ISSUE THREAD

**Issue by rnguillory** [gtrj0527/CSCI4125#14]
Development Task 8.iii.

**Comment by gtrj0527** [comment]
Verify if this person has every skill required by the given POS_CODE

**Comment by gtrj0527** [comment]
public LinkedList<Person> isQualified(Connection conn) {
        LinkedList<Person> qualifiedPeople = new LinkedList<Person>();
        try {
            String query = "SELECT pers_id
                                      FROM (SELECT * FROM has_skill hs1 WHERE pers_id = ?) hs1
                           "WHERE NOT EXISTS " +
                           "   (SELECT * " +
                           "    FROM position_skills ps1 " +
                           "    WHERE pos_code = ? " +
                           "    AND NOT EXISTS " +
                           "         (SELECT * " +
                           "          FROM has_skill hs2 " +
                           "          WHERE hs1.pers_id = hs2.pers_id " +
                           "          AND   hs2.ks_code = ps1.ks_code))";
            PreparedStatement isQualified = conn.prepareStatement(query);
            isQualified.setInt(1,this.pos_code);
            ResultSet rs = isQualified.executeQuery();
            return rs.next();
            }
        } catch (SQLException sqlEx) {
            System.err.println(sqlEx.toString());
        }
        return qualifiedPeople;
    }

**Comment by gtrj0527** [comment]
Done, 20180418.
