### ISSUE TITLE
Person List Qualified Job Categories

### ISSUE THREAD

**Issue by rnguillory** [gtrj0527/CSCI4125#15]
Development Task 8 b), Query 13

**Comment by gtrj0527** [comment]
If a skill gap is identified, propose a training plan for this person.
b) A person's job hunting; could be an interface for Queries 13 and 14

**Comment by JeriMarch** [comment]
Question:

@rnguillory @gtrj0527 : is this task almost complete? Specifically, is this task completed by the Qualification Tester class that Rachel built?

**Comment by JeriMarch** [comment]
@rnguillory 
NOTE: @gtrj0527  worked on "unwinding" the views category_skills, reelvant_category_skills, missing_category_skills, and category_qual from Create_Views.sql into  a big WITH CLAUSE with nested Select statements.  It works and retrieves (probably) correct cat_code that person is qualified for. 





> /*13. Given a person?s identifier, list all the job categories that a person is qualified for. ++++*/
> SELECT cat_code 
> FROM category_qual 
> WHERE pers_id = 7;

**Comment by gtrj0527** [comment]
NOTE: Current ClassCreation branch contains a method within JobCategory that fulfills the requirements of this task.

**Comment by rnguillory** [comment]
Pushed to ClassCreation, tested in QualificationTester.
