### ISSUE TITLE
Person findHighestPayPosition

### ISSUE THREAD

**Issue by rnguillory** [gtrj0527/CSCI4125#16]
Development Task 8 b) - Query 14

**Comment by gtrj0527** [comment]
If a skill gap is identified, propose a training plan for this person.
b) A person's job hunting; could be an interface for Query 14

**Comment by rnguillory** [comment]
Finally...  just needed a clear head.

**Comment by gtrj0527** [comment]
Great job! Thank you so much!!!

Gaby Swanson

On Fri, Apr 20, 2018, 18:50 rnguillory <notifications@github.com<mailto:notifications@github.com>> wrote:

Finally... just needed a clear head.
