### ISSUE TITLE
Person Training Plan position

### ISSUE THREAD

**Issue by rnguillory** [gtrj0527/CSCI4125#19]
Development Task 8a.iv.

**Comment by gtrj0527** [comment]
If a skill gap is identified, propose a training plan for this person.

**Comment by rnguillory** [comment]
Can we test, @gtrj0527 @JeriMarch, using the NewEmployeeApp, by making a person need more than one course to qualify for a job?  Or did we see that already?  If you guys don't have a chance today, I can try it today, or tonight after work.  If we can get that to work, I am pretty sure we are good to close this and the NewEmployeeApp issue.

**Comment by rnguillory** [comment]
We can close once we merge my pull request.  As well as the new employee app one.

**Comment by JeriMarch** [comment]
merged in. done.
