### ISSUE TITLE
Populate GICS table

### ISSUE THREAD

**Issue by gtrj0527** [gtrj0527/CSCI4125#23]

**Comment by rnguillory** [comment]
GICS Inserts created.  Lengthened 'code_description' field in 'GICS' to 500 characters in Create_Tables.sql, some descriptions are longer than 255 characters.

Pull request going up.

**Comment by gtrj0527** [comment]
Need to separate it out like we did zip_code and add drop to Create_Tables. Add script as well.

**Comment by gtrj0527** [comment]
Done by RNG on 20180418.
