### ISSUE TITLE
Update the queries with Dr. Tu's feedback

### ISSUE THREAD

**Issue by gtrj0527** [gtrj0527/CSCI4125#43]
The only ones left to update are Queries 20 and 24

**Comment by gtrj0527** [comment]
20 and 24 complete in ClassCreation branch. Just need to figure out how to get a single, unique answer from Queries 6 & 11. @rnguillory , please help!

**Comment by rnguillory** [comment]
16-18 done in positionFindQualifiedPeopleBranch.  Taking a look at 6 and 11.

**Comment by rnguillory** [comment]
Got 6 done.  Taking a break.  Will look at 11 a little later.

**Comment by gtrj0527** [comment]
Awesome. Thanks so much. You're the best!

**Comment by rnguillory** [comment]
Skill gap for a particular position:

SELECT ks_code
FROM position_skills
WHERE pos_code = 12
MINUS
(SELECT ks_code
FROM has_skill
WHERE pers_id = 12)

**Comment by rnguillory** [comment]
11 and 14 are still needed to be redone?  Or are there more to fix?  Not including 26 and 27 in the other issue.
