### ISSUE TITLE
NewEmployeeApp

### ISSUE THREAD

**Issue by rnguillory** [gtrj0527/CSCI4125#48]
Development 8a)

**Comment by gtrj0527** [comment]
Add query 9 to the app. Place it before query 12.

**Comment by rnguillory** [comment]
DROP SEQUENCE courseSet_seq;
CREATE SEQUENCE courseSet_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    NOCYCLE;
    
DROP TABLE courseSet;
CREATE TABLE courseSet(
    csetID NUMBER(8,0) PRIMARY KEY,
    c_code1 NUMBER(6,0),
    c_code2 NUMBER(6,0),
    c_code3 NUMBER(6,0),
    cSetSize NUMBER(2,0),
    cSetCost NUMBER(10,2));
    
--INSERT INTO courseSet(
--    SELECT courseSet_seq.NEXTVAL, c1.c_code, null, null, 1, c1.retail_price
--    FROM course c1);
    
INSERT INTO courseSet(
        SELECT courseSet_seq.NEXTVAL, c1.c_code, c2.c_code, null, 2, c1.retail_price + c2.retail_price
        FROM course c1, course c2
        WHERE c1.c_code < c2.c_code);
        
INSERT INTO courseSet(
        SELECT courseSet_seq.NEXTVAL, c1.c_code, c2.c_code, c3.c_code, 3,  c1.retail_price + c2.retail_price + c3.retail_price
        FROM course c1, course c2, course c3
        WHERE c1.c_code < c2.c_code
        AND c2.c_code < c3.c_code);          
          
DROP TABLE courseSet_skill;        
CREATE TABLE courseSet_skill(
    csetID NUMBER(8,0),
    ks_code VARCHAR(8)    
);
   
INSERT INTO courseSet_skill(csetID,ks_code)
    (SELECT csetID, ks_code
    FROM courseSet cSet1
    JOIN provides_skill cSkill1
        ON cSet1.c_code1 = cSkill1.c_code)
    UNION
    (SELECT csetID, ks_code
    FROM courseSet cSet2
    JOIN provides_skill cSkill2
        ON cSet2.c_code2 = cSkill2.c_code)
    UNION 
    (SELECT csetID, ks_code
    FROM courseSet cSet3
    JOIN provides_skill cSkill3
        ON cSet3.c_code3 = cSkill3.c_code);

WITH coverCSET AS (
SELECT csetID, csetSize FROM courseSet
WHERE NOT EXISTS (
SELECT ks_code FROM position_skills WHERE pos_code = 1
MINUS
SELECT ks_code FROM has_skill WHERE pers_id = 11
MINUS
SELECT ks_code FROM courseSet_skill
WHERE
courseSet.csetID = courseSet_skill.csetID
)
)
SELECT c_code1, c_code2, c_code3, csetsize, csetcost
FROM coverCSET
NATURAL JOIN courseSet
WHERE csetsize = (SELECT MIN(csetsize) FROM covercset NATURAL JOIN courseSet);

Try this one for 12. @gtrj0527

**Comment by gtrj0527** [comment]
@rnguillory , please take a look at this. Don't want to push to prevent breaking what's working.

else if (choice == 3) {       //training plan
                        boolean qualled = activePosition.isQualified(activePerson,conn);
                        if(qualled){
                            System.out.println("Person is qualified for this position.");
                        }
                        else {
                            try {
                                if(/*????*/) {         //if training plan can be covered by one course, use this
                                    LinkedList<Course> preTrngPlan = activePerson.preTrngPlan(activePosition, conn);
                                    Iterator<Course> preTrngPlanIterator = preTrngPlan.iterator();
                                    System.out.println("Lucky you - You need only one course to get the skills necessary" +
                                            "for this job!!!");
                                    Double totalPrice = 0.00;
                                    while (preTrngPlanIterator.hasNext()) {
                                        Course course = preTrngPlanIterator.next();
                                        totalPrice = course.getRetailPrice();
                                        System.out.println("Course title: " + course.getTitle() + ". Course cost: " +
                                                course.getRetailPrice() + ".");
                                    }
                                }
                                else{       //if training plan requires 2+ courses, use this
                                    LinkedList<Course> trainingPlan = activePerson.trainingPlan(activePosition, conn);
                                    Iterator<Course> trainingPlanIterator = trainingPlan.iterator();
                                    System.out.println("Suggested training plan: ");
                                    Double totalPrice = 0.00;
                                    while (trainingPlanIterator.hasNext()) {
                                        Course course = trainingPlanIterator.next();
                                        totalPrice += course.getRetailPrice();
                                        System.out.println("Course title: " + course.getTitle() + ". Course cost: " +
                                                course.getRetailPrice() + ".");
                                    }
                                    System.out.println("Total price for required courses: " + totalPrice);
                                }
                            }
                        }
                        activePosition = null;
                        activePerson = null;

**Comment by rnguillory** [comment]
That would work too, but I think to keep the code a bit simpler,
"trainingPlan" in Person should be a one stop shop, return either one or
multiple courses, depending on their needs.  If you look online, or pull
down my "newQuery12" branch, you'll see the updated "trainingPlan
function".  "NewEmployeeApp" didn't need to change in my implementation.
Also, in my branch, you'll see my updated query 9 and 12 that works in my
testing.  Jeri and I ran some tests that tested using personTakes to add
courses and skills to people which then removed that course from their
training plans.  That will likely be a test Dr. Tu wants to see.

I need to find out what additional things he wants me to demo for my stuff,
since some of the grad requirements overlap with some of the undergrad
requirements.  I am going to email him shortly.
